// ===== Comprehensive normalization maps for classes, teachers, locations =====

export const knownClasses = [
  "Studio Hosted Class", "Studio FIT", "Studio Back Body Blaze", "Studio Barre 57",
  "Studio Mat 57", "Studio Trainer's Choice", "Studio Cardio Barre Express",
  "Studio Amped Up!", "Studio HIIT", "Studio Foundations", "Studio SWEAT In 30",
  "Studio Cardio Barre Plus", "Studio Barre 57 Express", "Studio Cardio Barre",
  "Studio Back Body Blaze Express", "Studio Recovery", "Studio Pre/Post Natal",
  "Studio Mat 57 Express", "Studio PowerCycle", "Studio PowerCycle Express",
  "Studio FIT Express", "Studio HIIT Express", "Studio Foundations Express",
  "Studio SWEAT Express",
  "Studio Strength Lab", "Studio Strength Lab (Full Body)", "Studio Strength Lab (Push)",
  "Studio Strength Lab (Pull)", "Studio TABATA", "Studio ICY ISOMETRIC"
];

export const classNameMappings: Record<string, string> = {
  // Strength Lab variations
  'STRENGTH LAB (FULL BODY)': 'Studio Strength Lab (Full Body)',
  'STRENGTH LAB (PULL)': 'Studio Strength Lab (Pull)',
  'STRENGTH LAB (PUSH)': 'Studio Strength Lab (Push)',
  'STRENGTH (PULL)': 'Studio Strength Lab (Pull)',
  'STRENGTH (PUSH)': 'Studio Strength Lab (Push)',
  'STRENGTH (PULL': 'Studio Strength Lab (Pull)',
  'STRENGTH (PUSH': 'Studio Strength Lab (Push)',
  'STRENGTH (FULL BODY': 'Studio Strength Lab (Full Body)',
  'STRENGTH (FULL BODY)': 'Studio Strength Lab (Full Body)',
  'Strength Lab (Full body)': 'Studio Strength Lab (Full Body)',
  'Strength Lab (Full Body)': 'Studio Strength Lab (Full Body)',
  'Strength Lab (PUSH)': 'Studio Strength Lab (Push)',
  'Strength Lab (PULL)': 'Studio Strength Lab (Pull)',
  'Strength Lab (Push)': 'Studio Strength Lab (Push)',
  'Strength Lab (Pull)': 'Studio Strength Lab (Pull)',
  'STRENGTH LAB': 'Studio Strength Lab',
  'Strength Lab': 'Studio Strength Lab',
  'STRENGTH - FB': 'Studio Strength Lab (Full Body)',
  'STRENGTH - PULL': 'Studio Strength Lab (Pull)',
  'STRENGTH - PUSH': 'Studio Strength Lab (Push)',
  'Strength - FB': 'Studio Strength Lab (Full Body)',
  'Strength - Pull': 'Studio Strength Lab (Pull)',
  'Strength - Push': 'Studio Strength Lab (Push)',
  'strength - fb': 'Studio Strength Lab (Full Body)',
  'strength - pull': 'Studio Strength Lab (Pull)',
  'strength - push': 'Studio Strength Lab (Push)',

  // PowerCycle variations
  'powerCycle': 'Studio PowerCycle',
  'POWERCYCLE': 'Studio PowerCycle',
  'Powercycle': 'Studio PowerCycle',
  'PowerCycle': 'Studio PowerCycle',
  'POWER CYCLE': 'Studio PowerCycle',
  'Power Cycle': 'Studio PowerCycle',
  'CYCLE': 'Studio PowerCycle',
  'Cycle': 'Studio PowerCycle',
  'cycle': 'Studio PowerCycle',
  'powerCycle (EXPRESS)': 'Studio PowerCycle Express',
  'POWERCYCLE (EXPRESS)': 'Studio PowerCycle Express',
  'PowerCycle (Express)': 'Studio PowerCycle Express',
  'PowerCycle Express': 'Studio PowerCycle Express',
  'Powercycle Express': 'Studio PowerCycle Express',
  'powercycle express': 'Studio PowerCycle Express',
  'POWERCYCLE EXPRESS': 'Studio PowerCycle Express',
  'Cycle Exp': 'Studio PowerCycle Express',
  'CYCLE EXP': 'Studio PowerCycle Express',
  'cycle exp': 'Studio PowerCycle Express',

  // Barre 57
  'Barre 57': 'Studio Barre 57',
  'BARRE 57': 'Studio Barre 57',
  'Barre57': 'Studio Barre 57',
  'BARRE57': 'Studio Barre 57',
  'BARRES7': 'Studio Barre 57',
  'BARRE S7': 'Studio Barre 57',
  'barre 57': 'Studio Barre 57',
  'barre57': 'Studio Barre 57',
  'Barre 57 Express': 'Studio Barre 57 Express',
  'BARRE 57 EXPRESS': 'Studio Barre 57 Express',
  'BARRE 57 (EXPRESS)': 'Studio Barre 57 Express',
  'Barre57exp': 'Studio Barre 57 Express',
  'BARRE57EXP': 'Studio Barre 57 Express',
  'Barre 57 Exp': 'Studio Barre 57 Express',
  'BARRE 57 EXP': 'Studio Barre 57 Express',
  'barre 57 exp': 'Studio Barre 57 Express',
  'barre57 exp': 'Studio Barre 57 Express',
  'barre 57 express': 'Studio Barre 57 Express',

  // Cardio Barre
  'Cardio Barre': 'Studio Cardio Barre',
  'CARDIO BARRE': 'Studio Cardio Barre',
  'Cardio B': 'Studio Cardio Barre',
  'CARDIO B': 'Studio Cardio Barre',
  'CARDIOBARRE': 'Studio Cardio Barre',
  'cardio barre': 'Studio Cardio Barre',
  'cardio b': 'Studio Cardio Barre',
  'Cardio Barre Plus': 'Studio Cardio Barre Plus',
  'CARDIO BARRE PLUS': 'Studio Cardio Barre Plus',
  'CARDIOBARRE PLUS': 'Studio Cardio Barre Plus',
  'cardio barre plus': 'Studio Cardio Barre Plus',
  'Cardio B+': 'Studio Cardio Barre Plus',
  'CARDIO B+': 'Studio Cardio Barre Plus',
  'cardio b+': 'Studio Cardio Barre Plus',
  'Cardio Barre Express': 'Studio Cardio Barre Express',
  'CARDIO BARRE EXPRESS': 'Studio Cardio Barre Express',
  'Cardio Barre (Express)': 'Studio Cardio Barre Express',
  'CARDIOBARRE EXPRESS': 'Studio Cardio Barre Express',
  'cardio barre express': 'Studio Cardio Barre Express',
  'cardio barre exp': 'Studio Cardio Barre Express',
  'Cardio Barre Exp': 'Studio Cardio Barre Express',
  'CARDIO BARRE EXP': 'Studio Cardio Barre Express',
  'Cardio B Exp': 'Studio Cardio Barre Express',
  'CARDIO B EXP': 'Studio Cardio Barre Express',
  'Cardio B Express': 'Studio Cardio Barre Express',
  'CARDIO B EXPRESS': 'Studio Cardio Barre Express',
  'cardio b express': 'Studio Cardio Barre Express',
  'cardio b exp': 'Studio Cardio Barre Express',

  // Mat 57
  'Mat 57': 'Studio Mat 57',
  'MAT 57': 'Studio Mat 57',
  'Mat57': 'Studio Mat 57',
  'MAT57': 'Studio Mat 57',
  'MATS7': 'Studio Mat 57',
  'MAT S7': 'Studio Mat 57',
  'MATS57': 'Studio Mat 57',
  'MATS 57': 'Studio Mat 57',
  'mat 57': 'Studio Mat 57',
  'mat57': 'Studio Mat 57',
  'Mat 57 (Express)': 'Studio Mat 57 Express',
  'MAT 57 (EXPRESS)': 'Studio Mat 57 Express',
  'MAT57 (EXPRESS)': 'Studio Mat 57 Express',
  'MAT57 ( EXPRESS)': 'Studio Mat 57 Express',
  'MATS57 (EXPRESS)': 'Studio Mat 57 Express',
  'MAT 57 EXPRESS': 'Studio Mat 57 Express',
  'Mat57exp': 'Studio Mat 57 Express',
  'mat 57 express': 'Studio Mat 57 Express',
  'mat 57 exp': 'Studio Mat 57 Express',
  'mat57 exp': 'Studio Mat 57 Express',
  'Mat 57 Exp': 'Studio Mat 57 Express',
  'MAT 57 EXP': 'Studio Mat 57 Express',

  // FIT
  'Fit': 'Studio FIT',
  'FIT': 'Studio FIT',
  'FT': 'Studio FIT',
  'F IT': 'Studio FIT',
  'fit': 'Studio FIT',
  'FIT Express': 'Studio FIT Express',
  'Fit Express': 'Studio FIT Express',
  'fit express': 'Studio FIT Express',
  'FIT EXP': 'Studio FIT Express',
  'Fit Exp': 'Studio FIT Express',
  'fit exp': 'Studio FIT Express',

  // Back Body Blaze
  'Back Body Blaze': 'Studio Back Body Blaze',
  'BACK BODY BLAZE': 'Studio Back Body Blaze',
  'BBB': 'Studio Back Body Blaze',
  'bbb': 'Studio Back Body Blaze',
  'BACKBODYBLAZE': 'Studio Back Body Blaze',
  'back body blaze': 'Studio Back Body Blaze',
  'Back Body Blaze (Express)': 'Studio Back Body Blaze Express',
  'BACK BODY BLAZE (EXPRESS)': 'Studio Back Body Blaze Express',
  'BACK BODY BLAZE EXPRESS': 'Studio Back Body Blaze Express',
  'BACK BODY BLAZE EXPRES S': 'Studio Back Body Blaze Express',
  'BACKBODYBLAZE EXPRESS': 'Studio Back Body Blaze Express',
  'BBBexp': 'Studio Back Body Blaze Express',
  'Back Body Blaze Express': 'Studio Back Body Blaze Express',
  'back body blaze express': 'Studio Back Body Blaze Express',
  'BBB Express': 'Studio Back Body Blaze Express',
  'bbb express': 'Studio Back Body Blaze Express',
  'BBB Exp': 'Studio Back Body Blaze Express',
  'BBB EXP': 'Studio Back Body Blaze Express',
  'bbb exp': 'Studio Back Body Blaze Express',

  // Others
  'Foundations': 'Studio Foundations',
  'FOUNDATIONS': 'Studio Foundations',
  'foundations': 'Studio Foundations',
  'Foundations Express': 'Studio Foundations Express',
  'FOUNDATIONS EXPRESS': 'Studio Foundations Express',
  'foundations express': 'Studio Foundations Express',
  'Foundations Exp': 'Studio Foundations Express',
  'FOUNDATIONS EXP': 'Studio Foundations Express',
  'foundations exp': 'Studio Foundations Express',
  'Sweat in 30': 'Studio SWEAT In 30',
  'SWEAT IN 30': 'Studio SWEAT In 30',
  'sweat in 30': 'Studio SWEAT In 30',
  'Sweat': 'Studio SWEAT In 30',
  'SWEAT': 'Studio SWEAT In 30',
  'sweat': 'Studio SWEAT In 30',
  'SWEAT Express': 'Studio SWEAT Express',
  'Sweat Express': 'Studio SWEAT Express',
  'sweat express': 'Studio SWEAT Express',
  'SWEAT EXP': 'Studio SWEAT Express',
  'Sweat Exp': 'Studio SWEAT Express',
  'sweat exp': 'Studio SWEAT Express',
  'Recovery': 'Studio Recovery',
  'RECOVERY': 'Studio Recovery',
  'recovery': 'Studio Recovery',
  'Pre/Post Natal': 'Studio Pre/Post Natal',
  'PRE/POST NATAL': 'Studio Pre/Post Natal',
  'pre/post natal': 'Studio Pre/Post Natal',
  'Prenatal': 'Studio Pre/Post Natal',
  'PRENATAL': 'Studio Pre/Post Natal',
  'prenatal': 'Studio Pre/Post Natal',
  'HIIT': 'Studio HIIT',
  'Hiit': 'Studio HIIT',
  'hiit': 'Studio HIIT',
  'HIIT Express': 'Studio HIIT Express',
  'Hiit Express': 'Studio HIIT Express',
  'hiit express': 'Studio HIIT Express',
  'HIIT EXP': 'Studio HIIT Express',
  'Hiit Exp': 'Studio HIIT Express',
  'hiit exp': 'Studio HIIT Express',
  "Amped Up!": 'Studio Amped Up!',
  'AMPED UP': 'Studio Amped Up!',
  'AMPED UP!': 'Studio Amped Up!',
  'AMPEDUP': 'Studio Amped Up!',
  'amped up': 'Studio Amped Up!',
  'amped up!': 'Studio Amped Up!',
  "Trainer's Choice": "Studio Trainer's Choice",
  'TRAINERS CHOICE': "Studio Trainer's Choice",
  "trainer's choice": "Studio Trainer's Choice",
  'Hosted Class': 'Studio Hosted Class',
  'HOSTED CLASS': 'Studio Hosted Class',
  'hosted class': 'Studio Hosted Class',
  'Hosted': 'Studio Barre 57',
  'hosted': 'Studio Barre 57',
  'TABATA': 'Studio TABATA',
  'Tabata': 'Studio TABATA',
  'tabata': 'Studio TABATA',
  'ICY ISOMETRIC': 'Studio ICY ISOMETRIC',

  // Theme classes -> base class
  'SLAY GLUTES GALORE': 'Studio Barre 57',
  'BATTLE OF THE BANDS': 'Studio Barre 57',
  'BATTLE OF THE BANDS BARRE 57': 'Studio Barre 57',
  'SLAY GLUTES GALORE BARRE 57': 'Studio Barre 57',
  'SLAY GLUTES': 'Studio Barre 57',
  'GLUTES GALORE': 'Studio Barre 57',
};

export const teacherNameMappings: Record<string, string> = {
  "Nishant": "Nishanth Raj",
  "Nishanth": "Nishanth Raj",
  "nishant": "Nishanth Raj",
  "Karanvir": "Karanvir Bhatia",
  "Karan": "Karan Bhatia",
  "Vivaran": "Vivaran Dhasmana",
  "Kajol": "Kajol Kanchan",
  "Shruti": "Shruti Kulkarni",
  "Shruti K": "Shruti Kulkarni",
  "shruti k": "Shruti Kulkarni",
  "Richard": "Richard D'Costa",
  "Richy": "Richard D'Costa",
  "richy": "Richard D'Costa",
  "Reshma": "Reshma Sharma",
  "Pranjali": "Pranjali Jain",
  "Pramal": "Pranjali Jain",
  "Mrigakshi": "Mrigakshi Jaiswal",
  "Mrigakeni": "Mrigakshi Jaiswal",
  "Mriga": "Mrigakshi Jaiswal",
  "mriga": "Mrigakshi Jaiswal",
  "Janhavi": "Janhavi Jain",
  "Atulan": "Atulan Purohit",
  "Awlan": "Atulan Purohit",
  "Anisha": "Anisha Shah",
  "Upasna": "Upasna Paranjpe",
  "Rohan": "Rohan Dahima",
  "Saniya": "Saniya Jaiswal",
  "Cauveri": "Cauveri Vikrant",
  "Cawveri": "Cauveri Vikrant",
  "Kaveri": "Cauveri Vikrant",
  "Kabir": "Kabir Varma",
  "Simonelle": "Simonelle De Vitre",
  "Simonnelle": "Simonelle De Vitre",
  "Simonellle": "Simonelle De Vitre",
  "Simran": "Simran Dutt",
  "Anmol": "Anmol Sharma",
  "Bret": "Bret Saldanha",
  "Raunak": "Raunak Khemuka",
  "Raunaq": "Raunak Khemuka",
  "raunaq": "Raunak Khemuka",
  "Pushyank": "Pushyank Nahar",
  "Poojitha": "Poojitha Bhaskar",
  "Siddhartha": "Siddhartha Kusuma",
  "Sovena": "Sovena Fernandes",
  "Sov": "Sovena Fernandes",
  "sov": "Sovena Fernandes",
  "Chaitanya": "Chaitanya Nahar",
  "Veena": "Veena Narasimhan",
  "Shruti Suresh": "Shruti Suresh",
  "Shruti Kulkarni": "Shruti Kulkarni",
};

export const knownTeachers = [
  "Anisha Shah", "Atulan Purohit", "Janhavi Jain", "Karanvir Bhatia", "Karan Bhatia",
  "Mrigakshi Jaiswal", "Pranjali Jain", "Reshma Sharma", "Richard D'Costa",
  "Rohan Dahima", "Upasna Paranjpe", "Saniya Jaiswal",
  "Vivaran Dhasmana", "Nishanth Raj", "Cauveri Vikrant", "Kabir Varma",
  "Simonelle De Vitre", "Simran Dutt", "Anmol Sharma", "Bret Saldanha",
  "Raunak Khemuka", "Kajol Kanchan", "Pushyank Nahar", "Shruti Kulkarni",
  "Shruti Suresh", "Poojitha Bhaskar", "Siddhartha Kusuma",
  "Chaitanya Nahar", "Veena Narasimhan", "Sovena Fernandes"
];

export const locationMappings: Record<string, string> = {
  "Kwality House": "Kwality House, Kemps Corner",
  "Kemps Corner": "Kwality House, Kemps Corner",
  "Kemps": "Kwality House, Kemps Corner",
  "KEMPS": "Kwality House, Kemps Corner",
  "KEMPS CORNER": "Kwality House, Kemps Corner",
  "KC": "Kwality House, Kemps Corner",
  "kemps": "Kwality House, Kemps Corner",
  "kemps corner": "Kwality House, Kemps Corner",
  "Supreme HQ": "Supreme HQ, Bandra",
  "Bandra": "Supreme HQ, Bandra",
  "BANDRA": "Supreme HQ, Bandra",
  "bandra": "Supreme HQ, Bandra",
  "Kenkere": "Kenkere House",
  "KENKERE": "Kenkere House",
  "kenkere": "Kenkere House",
  "Kenkere House": "Kenkere House",
  "Annex": "Kwality House, Kemps Corner",
  "ANNEX": "Kwality House, Kemps Corner",
  "annex": "Kwality House, Kemps Corner",
  "South United": "South United Football Club",
  "South United Football Club": "South United Football Club",
  "south united": "South United Football Club",
  "Willingdon": "The Wellingdon Club",
  "WILLINGDON": "The Wellingdon Club",
  "willingdon": "The Wellingdon Club",
  "Wellingdon": "The Wellingdon Club",
  "WELLINGDON": "The Wellingdon Club",
  "wellingdon": "The Wellingdon Club",
  "The Wellingdon Club": "The Wellingdon Club",
  "Courtside": "Courtside",
  "COURTSIDE": "Courtside",
  "courtside": "Courtside",
  "Copper + Cloves": "The Studio by Copper + Cloves",
  "Copper Cloves": "The Studio by Copper + Cloves",
  "copper cloves": "The Studio by Copper + Cloves",
  "WeWork Galaxy": "WeWork Galaxy",
  "wework galaxy": "WeWork Galaxy",
  "WeWork Prestige": "WeWork Prestige Central",
  "wework prestige": "WeWork Prestige Central",
  "Outdoor Pop-up": "Physique Outdoor Pop-up",
  "Physique": "Physique Outdoor Pop-up",
  "physique": "Physique Outdoor Pop-up",
};

export const knownLocations = [
  "Kwality House, Kemps Corner",
  "Supreme HQ, Bandra",
  "Kenkere House",
  "South United Football Club",
  "The Wellingdon Club",
  "Courtside",
  "The Studio by Copper + Cloves",
  "WeWork Galaxy",
  "WeWork Prestige Central",
  "Physique Outdoor Pop-up"
];

// Class level categorization based on normalized names
export const classLevels: Record<string, 'beginner' | 'intermediate' | 'advanced'> = {
  'Studio Barre 57': 'beginner',
  'Studio Barre 57 Express': 'beginner',
  'Studio PowerCycle': 'beginner',
  'Studio PowerCycle Express': 'beginner',
  'Studio Foundations': 'beginner',
  'Studio Foundations Express': 'beginner',
  'Studio Recovery': 'beginner',
  'Studio Pre/Post Natal': 'beginner',
  'Studio Cardio Barre': 'intermediate',
  'Studio Cardio Barre Plus': 'intermediate',
  'Studio Cardio Barre Express': 'intermediate',
  'Studio Mat 57': 'intermediate',
  'Studio Mat 57 Express': 'intermediate',
  'Studio FIT': 'intermediate',
  'Studio FIT Express': 'intermediate',
  'Studio Back Body Blaze': 'intermediate',
  'Studio Back Body Blaze Express': 'intermediate',
  'Studio Strength Lab': 'intermediate',
  'Studio Strength Lab (Full Body)': 'intermediate',
  'Studio Strength Lab (Push)': 'intermediate',
  'Studio Strength Lab (Pull)': 'intermediate',
  'Studio SWEAT In 30': 'intermediate',
  'Studio SWEAT Express': 'intermediate',
  'Studio HIIT': 'advanced',
  'Studio HIIT Express': 'advanced',
  'Studio Amped Up!': 'advanced',
  'Studio TABATA': 'advanced',
  'Studio ICY ISOMETRIC': 'advanced',
  "Studio Trainer's Choice": 'intermediate',
  'Studio Hosted Class': 'beginner',
};
